services:
  caddy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./static:/srv
      - caddy_data:/data
      - caddy_config:/config

  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WAKAPI_PASSWORD_SALT=${WAKAPI_PASSWORD_SALT}
    volumes:
      - wakapi_data:/data

  remark42:
    image: ghcr.io/umputun/remark42:latest
    restart: unless-stopped
    container_name: "remark42"
    environment:
      - REMARK_URL=https://remark42.inogai.com
      - SITE=remark
      - SECRET=${REMARK42_SECRET}
      - AUTH_ANON=true
      - AUTH_GITHUB_CID=${REMARK42_GITHUB_CID} # OAuth2 client ID
      - AUTH_GITHUB_CSEC=${REMARK42_GITHUB_CSEC} # OAuth2 client secret
    volumes:
      - remark42_data:/srv/var

volumes:
  caddy_data:
  caddy_config:
  wakapi_data:
  remark42_data:
